### ISSUE TITLE
Kapitel 4: Luftbilder HSR

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/photogrammetry-evaluation#8]
Grösstenteils fertig, seit 558ef80 und 7175440.

@schmijos, kannst du den aktuellen Stand mal reviewen?

**Comment by schmijos** [comment]
Ich schaus heute Abend an.

**Comment by schmijos** [comment]
Sieht gut aus.

**Comment by dbrgn** [comment]
- Georeferenzierung erwähnen: https://github.com/OpenDroneMap/OpenDroneMap/issues/144#issuecomment-130810923
- Docker erwähnen, ist merged: https://github.com/OpenDroneMap/OpenDroneMap/pull/143
